import { env } from "cloudflare:workers";
import { cookies } from "next/headers";
import { getAdminUser } from "../../admin-auth";
import { readImage, imageResponse, UploadError } from "../../../lib/upload";
import generatePayload from "promptpay-qr";
import QRCode from "qrcode";
export const dynamic="force-dynamic";
function db(){if(!env.DB)throw new Error("DATABASE_UNAVAILABLE");return env.DB;}
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{"Cache-Control":"no-store"}});
class Problem extends Error { constructor(public code:number,message:string){super(message)} }
function fail(code:number,message:string):never{throw new Problem(code,message)}
async function admin(){const user=await getAdminUser();if(!user)fail(403,"กรุณาเข้าสู่ระบบด้วยบัญชีเจ้าของร้าน");return user;}
async function token(){const c=await cookies();let value=c.get("mint-customer")?.value;if(!value||!/^[a-f0-9-]{36}$/.test(value)){value=crypto.randomUUID();c.set("mint-customer",value,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:60*60*24*90});}return value;}
function text(v:unknown,max=100){if(typeof v!=="string"||v.length>max)fail(400,"ข้อมูลไม่ถูกต้อง");return v.trim();}
function integer(v:unknown,min:number,max:number){if(typeof v!=="number"||!Number.isInteger(v)||v<min||v>max)fail(400,"จำนวนหรือราคาไม่ถูกต้อง");return v;}
async function body(req:Request):Promise<any>{if(Number(req.headers.get("content-length")??0)>20000)fail(413,"ข้อมูลมีขนาดใหญ่เกินไป");try{const b=await req.json();if(!b||typeof b!=="object"||Array.isArray(b))fail(400,"ข้อมูลไม่ถูกต้อง");return b}catch{fail(400,"ข้อมูลไม่ถูกต้อง")}}
async function init(){const existing=await db().prepare("SELECT id FROM settings WHERE id=1").first();if(existing)return;
const seed=[["pork","หมูสามชั้น","นุ่มฉ่ำ หอมเครื่องเทศ","เนื้อสัตว์",1000,42,"/images/pork-belly.png"],["sausage","ไส้กรอก","กรอบนอก นุ่มใน","ลูกชิ้น & ไส้กรอก",1000,30,"/images/mala-hero.png"],["enoki","เห็ดเข็มทอง","กรุบกรอบ คลุกเครื่องเทศ","ผัก & เห็ด",1000,18,"/images/bacon-enoki.png"],["bacon","เบคอนพันเห็ด","เบคอนหอม ๆ พันเห็ดเข็มทอง","เนื้อสัตว์",1500,0,"/images/bacon-enoki.png"],["fishball","ลูกชิ้นปลา","เนื้อปลาเด้ง ๆ ย่างร้อน ๆ","ลูกชิ้น & ไส้กรอก",1000,13,"/images/mala-hero.png"]];
await db().batch([db().prepare("INSERT OR IGNORE INTO settings(id,name,target,recipient,open) VALUES(1,'Mint','','',1)"),...seed.map((p,i)=>db().prepare("INSERT OR IGNORE INTO products(id,name,description,category,price,stock,image,active,position) VALUES(?,?,?,?,?,?,?,1,?)").bind(...p,i))]);}
async function expire(){await db().prepare("UPDATE orders SET status='CANCELLED' WHERE status='PENDING' AND payment IN ('UNPAID','REJECTED') AND expires < ?").bind(Date.now()).run();}
async function owned(id:string,isAdmin=false){const row=await db().prepare(isAdmin?"SELECT * FROM orders WHERE id=?":"SELECT * FROM orders WHERE id=? AND token=?").bind(...(isAdmin?[id]:[id,await token()])).first<any>();if(!row)fail(404,"ไม่พบออเดอร์นี้");return row;}

async function handle(req:Request){
const path=new URL(req.url).pathname.replace(/^\/api\//,"").split("/").map(decodeURIComponent);const action=path[0],id=path[1];
if(req.method!=="GET"){if(req.headers.get("x-mint-action")!=="1")fail(403,"คำขอไม่ถูกต้อง");const origin=req.headers.get("origin");if(origin&&origin!==new URL(req.url).origin)fail(403,"คำขอไม่ถูกต้อง");}
await init();await expire();
if(action==="catalog"&&req.method==="GET"){const s=await db().prepare("SELECT * FROM settings WHERE id=1").first<any>();return json({products:(await db().prepare("SELECT * FROM products WHERE active=1 ORDER BY position,name").all()).results,settings:{name:s.name,open:s.open,paymentReady:!!(s.target&&s.recipient)}});}
if(action==="customer"&&req.method==="POST"){const b=await body(req);const name=text(b.name,60);if(!name)fail(400,"กรุณากรอกชื่อของคุณ");await token();return json({name});}
if(action==="orders"&&req.method==="POST"){
const b=await body(req),customer=text(b.customer,60),note=text(b.note??"",300),spicy=text(b.spicy,20),orderId=text(b.id,36),customerToken=await token();
if(!customer||!["ไม่เผ็ด","เผ็ดน้อย","เผ็ดกลาง","เผ็ดมาก"].includes(spicy)||!/^[a-f0-9-]{36}$/.test(orderId))fail(400,"กรุณาตรวจสอบชื่อและความเผ็ด");
const duplicate=await db().prepare("SELECT id FROM orders WHERE id=? AND token=?").bind(orderId,customerToken).first();if(duplicate)return json(duplicate);
const settings=await db().prepare("SELECT * FROM settings WHERE id=1").first<any>();if(!settings.open)fail(409,"ร้านปิดรับออเดอร์ชั่วคราว");if(!settings.target||!settings.recipient)fail(409,"ร้านยังไม่ได้ตั้งค่าบัญชีรับเงิน");
if(!Array.isArray(b.items)||b.items.length<1||b.items.length>24)fail(400,"กรุณาเลือกเมนู");
const seen=new Set();const products=[];let total=0;
for(const item of b.items){const pid=text(item.id,36),qty=integer(item.qty,1,100);if(seen.has(pid))fail(400,"เมนูซ้ำ");seen.add(pid);const p=await db().prepare("SELECT * FROM products WHERE id=? AND active=1").bind(pid).first<any>();if(!p||p.stock<qty)fail(409,`เมนู ${p?.name??pid} มีสต็อกไม่เพียงพอ กรุณาปรับตะกร้า`);products.push({...p,qty});total+=p.price*qty;}
const now=Date.now();
try{await db().batch([db().prepare("INSERT INTO orders(id,token,customer,total,status,payment,note,spicy,created,expires,target,recipient) VALUES(?,?,?,?,'PENDING','UNPAID',?,?,?,?,?,?)").bind(orderId,customerToken,customer,total,note,spicy,now,now+15*60*1000,settings.target,settings.recipient),...products.map(p=>db().prepare("INSERT INTO order_items(order_id,product_id,name,price,qty) VALUES(?,?,?,?,?)").bind(orderId,p.id,p.name,p.price,p.qty))]);}catch(error){if(String(error).includes("STOCK_UNAVAILABLE"))fail(409,"มีออเดอร์อื่นสั่งสินค้านี้แล้ว กรุณาปรับตะกร้า");const same=await db().prepare("SELECT id FROM orders WHERE id=? AND token=?").bind(orderId,customerToken).first();if(same)return json(same);throw error;}
return json({id:orderId},201);}
if(action==="orders"&&req.method==="GET"){
if(id){const row=await owned(id);const result={...row,token:undefined,slip:row.slip?true:null,items:(await db().prepare("SELECT product_id,name,price,qty FROM order_items WHERE order_id=?").bind(id).all()).results};return json(result);}
return json((await db().prepare("SELECT id,customer,total,status,payment,created FROM orders WHERE token=? ORDER BY created DESC LIMIT 30").bind(await token()).all()).results);}
if(action==="qr"&&req.method==="GET"){const o=await owned(id);if(o.status==="CANCELLED"||o.payment==="PAID")fail(409,"ออเดอร์นี้ไม่ต้องชำระเงิน");const svg=await QRCode.toString(generatePayload(o.target,{amount:o.total/100}),{type:"svg",margin:4,errorCorrectionLevel:"M",width:320});return new Response(svg,{headers:{"Content-Type":"image/svg+xml","Cache-Control":"private,no-store","X-Content-Type-Options":"nosniff"}});}
if(action==="payment"&&req.method==="POST"){const o=await owned(id);if(o.status!=="PENDING"||!["UNPAID","REJECTED"].includes(o.payment))fail(409,"ออเดอร์นี้ส่งสลิปไม่ได้แล้ว");const f=await readImage(req),key=`slips/${id}/${crypto.randomUUID()}`;const result=await db().batch([db().prepare("UPDATE orders SET slip=?,slip_type=?,payment='SUBMITTED' WHERE id=? AND status='PENDING' AND payment IN ('UNPAID','REJECTED') AND expires>=?").bind(key,f.type,id,Date.now()),db().prepare("INSERT INTO uploads(id,type,data) SELECT ?,?,? WHERE changes()=1").bind(key,f.type,f.buffer),db().prepare("DELETE FROM uploads WHERE id=? AND EXISTS(SELECT 1 FROM orders WHERE id=? AND slip=?)").bind(o.slip??'',id,key)]);if(!result[0].meta.changes)fail(409,"ออเดอร์เปลี่ยนสถานะแล้ว");return json({payment:"SUBMITTED"});}
if(action==="cancel"&&req.method==="POST"){await owned(id);const r=await db().prepare("UPDATE orders SET status='CANCELLED' WHERE id=? AND status='PENDING' AND payment IN ('UNPAID','REJECTED')").bind(id).run();if(!r.meta.changes)fail(409,"กรุณาติดต่อร้านเพื่อยกเลิกออเดอร์ที่ส่งสลิปแล้ว");return json({ok:true});}
if(action==="slip"&&req.method==="GET"){await admin();const o=await owned(id,true);if(!o.slip)fail(404,"ไม่พบสลิป");return imageResponse(o.slip,true);}
if(action==="image"&&req.method==="GET"){if(!id||!/^[a-f0-9-]{36}$/.test(id))fail(404,"ไม่พบรูปภาพ");return imageResponse("products/"+id,false);}
if(action!=="admin")fail(404,"ไม่พบข้อมูล");await admin();const sub=path[1],oid=path[2];
if(req.method==="GET"){const all=(await db().prepare("SELECT * FROM orders ORDER BY created DESC LIMIT 200").all<any>()).results;const itemRows=(await db().prepare("SELECT order_id,product_id,name,price,qty FROM order_items WHERE order_id IN (SELECT id FROM orders ORDER BY created DESC LIMIT 200)").all<any>()).results;const todayStart=new Date(new Date(Date.now()+7*3600000).toISOString().slice(0,10)+"T00:00:00+07:00").getTime();const summary=await db().prepare("SELECT COUNT(*) AS count,COALESCE(SUM(CASE WHEN payment='PAID' THEN total ELSE 0 END),0) AS revenue FROM orders WHERE created>=? AND status!='CANCELLED'").bind(todayStart).first();return json({orders:all.map(o=>({...o,token:undefined,items:itemRows.filter(i=>i.order_id===o.id)})),products:(await db().prepare("SELECT * FROM products ORDER BY position,name").all()).results,settings:await db().prepare("SELECT * FROM settings WHERE id=1").first(),summary,movements:(await db().prepare("SELECT m.*,p.name FROM stock_movements m JOIN products p ON p.id=m.product_id ORDER BY m.id DESC LIMIT 50").all()).results});}
const b=await body(req);
if(sub==="settings"){const name=text(b.name,60),target=text(b.target,20).replace(/[ -]/g,""),recipient=text(b.recipient,100);if(!name||target&&!/^(0[689]\d{8}|\d{13})$/.test(target)||target&&!recipient)fail(400,"กรอกชื่อร้าน เบอร์ PromptPay 10 หลัก หรือเลขประจำตัว 13 หลัก และชื่อผู้รับเงิน");await db().prepare("UPDATE settings SET name=?,target=?,recipient=?,open=? WHERE id=1").bind(name,target,recipient,b.open?1:0).run();return json({ok:true});}
if(sub==="product"){const pid=b.id?text(b.id,36):crypto.randomUUID(),name=text(b.name,80),description=text(b.description??"",200),category=text(b.category,40),image=text(b.image??"",500),price=integer(b.price,100,100000),stock=integer(b.stock,0,100000);if(!name||!category||image&&!/^(\/images\/|\/api\/image\/|https:\/\/)/.test(image))fail(400,"ตรวจสอบชื่อ หมวดหมู่ และ URL รูปภาพ");
const old=await db().prepare("SELECT stock FROM products WHERE id=?").bind(pid).first<any>();const now=Date.now();
const expected=old?integer(b.expectedStock,0,100000):0;
const result=await db().batch([db().prepare("INSERT INTO products(id,name,description,category,price,stock,active,image,position) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,price=excluded.price,stock=excluded.stock,active=excluded.active,image=excluded.image WHERE products.stock=?").bind(pid,name,description,category,price,stock,b.active?1:0,image,integer(b.position??0,0,999),expected),db().prepare("INSERT INTO stock_movements(product_id,delta,reason,created) SELECT ?,?,'ปรับสต็อกโดยร้าน',? WHERE changes()=1").bind(pid,stock-expected,now)]);
if(!result[0].meta.changes)fail(409,"สต็อกมีการเปลี่ยนแปลง กรุณารีเฟรชแล้วบันทึกใหม่");return json({id:pid});}
if(sub==="order"){const o=await owned(oid,true);const act=text(b.action,20);if(act==="approve"){if(o.payment!=="SUBMITTED"||o.status!=="PENDING")fail(409,"ออเดอร์นี้ไม่ได้รอตรวจสลิป");await db().prepare("UPDATE orders SET payment='PAID',status='ACCEPTED' WHERE id=? AND payment='SUBMITTED' AND status='PENDING'").bind(oid).run();}
else if(act==="reject"){if(o.payment!=="SUBMITTED"||o.status!=="PENDING")fail(409,"ออเดอร์นี้ไม่ได้รอตรวจสลิป");await db().prepare("UPDATE orders SET payment='REJECTED',expires=? WHERE id=? AND payment='SUBMITTED'").bind(Date.now()+15*60000,oid).run();}
else{const next:Record<string,string>={ACCEPTED:"COOKING",COOKING:"READY",READY:"COMPLETED"};if(act!==next[o.status]||o.payment!=="PAID")fail(409,"สถานะออเดอร์เปลี่ยนไปแล้ว กรุณารีเฟรช");await db().prepare("UPDATE orders SET status=? WHERE id=? AND status=? AND payment='PAID'").bind(act,oid,o.status).run();}return json({ok:true});}
fail(404,"ไม่พบข้อมูล");}
async function wrapped(req:Request){try{return await handle(req)}catch(e){if(e instanceof Problem)return json({error:e.message},e.code);if(e instanceof UploadError)return json({error:e.message},e.status);console.error("Mint API error",e);return json({error:"ระบบยังไม่พร้อม กรุณาลองอีกครั้ง ข้อมูลของคุณยังอยู่"},503);}}
export const GET=wrapped;export const POST=wrapped;
