import { sqliteTable, text, integer, index, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
export const adminSessions = sqliteTable("admin_sessions", { id:text("id").primaryKey(), ownerEmail:text("owner_email").notNull(), passwordVersion:text("password_version").notNull(), expires:integer("expires").notNull() });
export const loginLimits = sqliteTable("login_limits", { id:text("id").primaryKey(), attempts:integer("attempts").notNull(), expires:integer("expires").notNull() });
export const settings = sqliteTable("settings", { id: integer("id").primaryKey(), name:text("name").notNull(), target:text("target").notNull().default(""), recipient:text("recipient").notNull().default(""), open:integer("open").notNull().default(1) });
export const products = sqliteTable("products", { id:text("id").primaryKey(), name:text("name").notNull(), description:text("description").notNull().default(""), category:text("category").notNull(), price:integer("price").notNull(), stock:integer("stock").notNull(), active:integer("active").notNull().default(1), image:text("image").notNull().default(""), position:integer("position").notNull().default(0) },t=>[check("stock_nonnegative",sql`${t.stock} >= 0`),check("price_positive",sql`${t.price} > 0`)]);
export const orders = sqliteTable("orders",{ id:text("id").primaryKey(), token:text("token").notNull(), customer:text("customer").notNull(), total:integer("total").notNull(), status:text("status").notNull().default("PENDING"), payment:text("payment").notNull().default("UNPAID"), note:text("note").notNull().default(""), spicy:text("spicy").notNull(), created:integer("created").notNull(), expires:integer("expires").notNull(), target:text("target").notNull(), recipient:text("recipient").notNull(), slip:text("slip"), slipType:text("slip_type") },t=>[index("idx_orders_created").on(t.created),index("idx_orders_token").on(t.token)]);
export const items = sqliteTable("order_items",{ id:integer("id").primaryKey({autoIncrement:true}), orderId:text("order_id").notNull().references(()=>orders.id), productId:text("product_id").notNull().references(()=>products.id), name:text("name").notNull(), price:integer("price").notNull(), qty:integer("qty").notNull() },t=>[index("idx_items_order_id").on(t.orderId),check("qty_positive",sql`${t.qty} > 0`)]);
export const movements = sqliteTable("stock_movements",{id:integer("id").primaryKey({autoIncrement:true}),productId:text("product_id").notNull().references(()=>products.id),delta:integer("delta").notNull(),reason:text("reason").notNull(),orderId:text("order_id"),created:integer("created").notNull()});
